# Generated by Django 3.1.1 on 2020-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='a4850f2c22', editable=False, max_length=10),
        ),
    ]
