# Generated by Django 3.1.1 on 2020-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201006_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='b96f28a87f', editable=False, max_length=10),
        ),
    ]
